### ISSUE TITLE
not working, bad syntaxe ?

### ISSUE THREAD

**Issue by antlep** [itsbrianburton/slide-confirm#1]
Hello,

I tried to add it into my dashboard

```
type: custom:slide-confirm-card
sliders:
  - name: Mode Sentinel
    icon: mdi:dog
    textUnconfirmed: Mode Sentinelle désactivé
    textConfirmed: Mode Sentinelle activé
    iconUnconfirmed: mdi:dog-side-off
    iconConfirmed: mdi:lock-open
    confirm_action:
      action: call-service
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.mode_sentinelle
``` 

but the slider doesn't seems to work, the front is reacting but my boolean doesn't switch states
