### ISSUE TITLE
Better sections compatibility

### ISSUE THREAD

**Issue by dnestico** [itsbrianburton/slide-confirm#3]
Just discovered this card recently and it's great.. but I think it needs better sections dashboard compatibility, like maybe make the font size dynamic so it shrinks with the card.

My current code using the "layout" tab on the card editor.

```
type: custom:slide-confirm-card
sliders:
  - name: Bright
    icon: mdi:brightness-7
    textUnconfirmed: Activate scene
    textConfirmed: Scene Activated!
    iconUnconfirmed: hue:logo
    iconConfirmed: mdi:brightness-7
    confirm_action:
      action: call-service
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.slide_confirm
grid_options:
  columns: 6
  rows: auto
```

<img width="198" alt="Image" src="https://github.com/user-attachments/assets/31850fec-c7aa-4ef8-8a2a-52307f7f78cc" />
