### ISSUE TITLE
Problems with action

### ISSUE THREAD

**Issue by dllfpp** [itsbrianburton/slide-confirm#6]
Below code is not working:

```
type: custom:slide-confirm-card
sliders:
- name: null
  icon: null
  textUnconfirmed: LUCE DISPENSA
  textConfirmed: Accesa
  iconUnconfirmed: mdi:lightbulb
  iconConfirmed: mdi:check
  confirm_action:
  action: switch.toggle
  data: {}
  target:
    entity_id: switch.luce_dispensa
```

Consider that the action part, in the Actions tab of the Developer Tools, is working fine:

```
action: switch.toggle
data: {}
target:
  entity_id: switch.luce_dispensa
```
