### ISSUE TITLE
[Feature Request] - Allow editable styles

### ISSUE THREAD

**Issue by BigFlubba** [itsbrianburton/slide-confirm#7]
I want the option for colors, sizes, & format to be editable. For example, I have this setup and I want the confirmed colors to be red for each and want to shrink the sizes because I have it in this layout. As you can see a single card takes up a lot of space.

![Image](https://github.com/user-attachments/assets/81ff1e10-1489-435d-9746-7365d4171c7a)
```
type: vertical-stack
cards:
  - type: media-control
    entity: media_player.big_flubba_pc
    name: My PC
  - square: false
    type: grid
    cards:
      - type: gauge
        severity:
          green: 0
          yellow: 50
          red: 75
        entity: sensor.big_flubba_pc_cpu_usage
        name: CPU Usage
      - type: gauge
        severity:
          green: 0
          yellow: 70
          red: 85
        entity: sensor.big_flubba_pc_ram_usage
        name: RAM Usage
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: button.big_flubba_pc_rgbon
        icon: mdi:lightbulb
        show_state: false
        name: RGB On
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: button.big_flubba_pc_rgboff
        icon: mdi:lightbulb-off-outline
        show_state: false
        name: RGB Off
    columns: 4
  - type: custom:slide-confirm-card
    sliders:
      - name: Lock
        icon: mdi:lock
        textUnconfirmed: Slide to Lock
        textConfirmed: PC Locking!
        iconUnconfirmed: mdi:lock-open
        iconConfirmed: mdi:lock
        confirm_action:
          action: call-service
          service: button.press
          target:
            entity_id: button.big_flubba_pc_lock
      - name: Sleep
        icon: mdi:moon-waning-crescent
        textUnconfirmed: Slide to Sleep
        textConfirmed: PC Going To Sleep!
        iconUnconfirmed: mdi:moon-waning-crescent
        iconConfirmed: mdi:moon-waning-crescent
        confirm_action:
          action: call-service
          service: button.press
          target:
            entity_id: button.big_flubba_pc_sleep
      - name: Hibernate
        icon: mdi:moon-waning-crescent
        textUnconfirmed: Slide to Hibernate
        textConfirmed: PC Entering Hibernation!
        iconUnconfirmed: mdi:moon-waning-crescent
        iconConfirmed: mdi:moon-waning-crescent
        confirm_action:
          action: call-service
          service: button.press
          target:
            entity_id: button.big_flubba_pc_hibernate
      - name: Restart
        icon: mdi:restart
        textUnconfirmed: Slide to Restart
        textConfirmed: PC Restarting!
        iconUnconfirmed: mdi:restart-off
        iconConfirmed: mdi:restart-alert
        confirm_action:
          action: call-service
          service: button.press
          target:
            entity_id: button.big_flubba_pc_restart
      - name: Shutdown
        icon: mdi:power
        textUnconfirmed: Slide to Shutdown
        textConfirmed: PC Shutting Down!
        iconUnconfirmed: mdi:power-on
        iconConfirmed: mdi:power-off
        confirm_action:
          action: call-service
          service: button.press
          target:
            entity_id: button.big_flubba_pc_shutdown
title: My PC
```
