### ISSUE TITLE
Auto-entities support

### ISSUE THREAD

**Issue by dnestico** [itsbrianburton/slide-confirm#8]
Trying to use this card with auto-entities for my light scenes but can't get it to work, maybe I'm doing it wrong. As you can see in the screenshot it technically is making the cards but I can't figure out how to make the parameters work so it can show the name of the scene's/entities and their icons, also then need the scene.turn_on service to also work but that can be figured out after.

Here's my code:
```
type: custom:auto-entities
filter:
  include:
    - domain: scene
      area: basement
      options:
        type: custom:slide-confirm-card
        sliders:
          - icon: mdi:brightness-7
            textUnconfirmed: Slide
            textConfirmed: Activated!
            iconUnconfirmed: hue:logo
            iconConfirmed: mdi:brightness-7
  exclude: []
sort:
  method: last_triggered
  reverse: false
  numeric: false
show_empty: false
card_param: sliders
card:
  type: custom:slide-confirm-card
```

<img width="468" alt="Image" src="https://github.com/user-attachments/assets/48594e67-5328-4393-95ee-329a5c32a400" />
